server:
  port: 7000
  servlet:
    context-path: /tansci

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Sa-Token 配置 (文档: https://sa-token.cc)
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# magic-api
magic-api:
  # 配置web页面入口
  web: /api/web
  # 配置文件存储位置
  resource:
    type: database # 配置存储在数据库中
    tableName: magic_api_file # 数据库中的表名
#    datasource: tansci_boot # 指定数据源（单数据源时无需配置，多数据源时默认使用主数据源，如果存在其他数据源中需要指定。）
    prefix: /tansci-api # key前缀
    readonly: false # 是否是只读模式
#    location: data/magic-api #存储路径
  prefix: / # 接口前缀，可以不配置
  show-sql: true # 配置打印SQL
  sql-column-case: camel # 启用驼峰命名转换
  cache:
    enable: true  #开启缓存，默认是不开启的
    ttl: 3600000 #有效期1小时，默认-1 即永不过期
  response-code:
    success: 200 #执行成功的code值
    invalid: 400 #参数验证未通过的code值
    exception: 500 #执行出现异常的code值
  date-pattern: # 配置请求参数支持的日期格式
    - yyyy-MM-dd
    - yyyy-MM-dd HH:mm:ss
    - yyyyMMddHHmmss
    - yyyyMMdd

# flowable
flowable:
  async-executor-activate: true # 关闭定时任务job
  database-schema-update: true # flowable自动更新表结构